apiVersion: v1
entries:
  lc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-28T08:21:38.10976977Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 7fc26330b526d65c9d90ec57601517ed3827a25f1ef4837a987cc0c3e7ec5fe0
    home: lc.zaakonline.nl
    icon: lc.zaakonline.nl
    name: lc
    urls:
    - lc-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-28T08:21:38.045464067Z"
