apiVersion: v1
entries:
  lc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-04T17:13:13.363654441Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: f2faf7f8b420fdce4d4c1f3066a12c603243b03f1e7200cf69af668e25ca9d2c
    home: lc.zaakonline.nl
    icon: lc.zaakonline.nl
    name: lc
    urls:
    - lc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-04T17:13:13.184262536Z"
